### ISSUE TITLE
关于数据结构

### ISSUE THREAD

**Issue by wenchaosong** [KunMinX/Linkage-RecyclerView#1]
这个是要和后台配合才能做到的,然而实际情况是后台有他们的框架或者做法,这就有一定的局限性

**Comment by KunMinX** [comment]
@wenchaosong 或许其他人也会对 所谓“局限性” 有类似的疑惑，我在此统一答疑下：

#### 1.该数据结构本身并不负责联动的功能。
该数据结构只是 普遍适用的 “Header / item” 结构。换言之，只要使用者打算展示分组数据，就必然绕不开这样的结构设计，而联动功能是 仅存在于代码层面的、附加的功能。

#### 2.使用联动必然涉及到分组。
如果不分组，必然不能延伸出联动；如果有联动需求，必然首先存在分组。

#### 综上，“存在局限性” 这种说法，是一种想当然、是并不存在的。
分组列表本来就是在移动端展示用，那么数据结构请务必与后端协商，结合移动端的实际展示需求来适配数据的。

**Comment by wenchaosong** [comment]
@KunMinX  第一点,这个数据结构已经具有了联动的基础,因为整合了全部数据.所以你说的第一点不负责联动功能其实不太正确,它已经负责了,只是看客户端有没有实现.
第二点,联动和分组是2个需求,参照淘宝商城,它的分类列表就没有联动,但是它也有分组

**Comment by KunMinX** [comment]
@wenchaosong 

#### 第一，我再次也是最后一次强调，这个数据结构是普适的分组数据结构。
联动只是代码层面额外编写的功能，数据结构本身不包含联动的功能。

#### 第二，联动是依托于分组的额外的存在。
有联动，必定有分组；有分组，未必要有联动。

#### 综上，既然有联动的需求，必然要使用到分组的数据结构。
而分组数据结构又是普适存在的，并不存在你最开始所说的 “局限性” 问题。

**Comment by jianghao1123** [comment]
GroupedItem写成接口比较好，人家的实体item继承你的接口，这样他就可以不用局限于json数据了

**Comment by KunMinX** [comment]
@jianghao1123 

实在看不出 “继承接口” 和 “局限于 JSON 数据” 有何因果关系。

JSON 只是结构化数据的方式之一，LinkageRecyclerView 并没有强制要求数据来源一定是 JSON，无论 XML，JSON，protocol buffer 还是何种方式，只要在能在移动端解析成 List<XXXGroupedItem> 即可。此外，联动逻辑依赖于抽象类中仅有的几个必填字段，用户自定义的 XXXGroupedItem 务必继承于抽象类 BaseGroupedItem。

**Comment by KunMinX** [comment]
公告：

我不反对提建议，但提建议时请务必客观、严谨。任何脱离实证依据的言论，都可能对其他使用者造成困扰，这是我一直以来致力于杜绝的。

**Comment by jianghao1123** [comment]
我的意思是 BaseGroupedItem 和 ItemInfo 如果做成是接口是不是会更好。

**Comment by KunMinX** [comment]
@jianghao1123 这个疑问，只有你自己来解答。不要将想法停留在脑海里，你有什么样的想法，就请务必按自己的思路将代码敲一遍，实证可行了，我们再根据你的代码讨论和改进。
