### ISSUE TITLE
请问 一级目录切换能否只要选中效果，我看demo目前效果是会从当前目录滚动到下一个目录

### ISSUE THREAD

**Issue by small-dream** [KunMinX/Linkage-RecyclerView#10]

**Comment by KunMinX** [comment]
@small-dream 你好。可以具体描述一下，“只要一级列表的选中效果，而不要二级列表定位到对应分组”，其背后的具体需求场景吗？
如果该需求合情合理，且确实普遍存在这样的场景，我将扩充该选项。
