### ISSUE TITLE
setScrollSmoothly 设置为false 列表好像无法联动了...

### ISSUE THREAD

**Issue by zzm123456** [KunMinX/Linkage-RecyclerView#11]
Demo 设置以后有的列表可以联动 有的不行

**Comment by KunMinX** [comment]
@zzm123456 你好，可以提供一下具体无法联动的页面的名称吗，这里暂时没有复现出来。

**Comment by zzm123456** [comment]
@KunMinX ElemeSampleFragment 这个页面 点击左侧栏无法联动右侧

**Comment by zzm123456** [comment]
....我知道了 是数据一模一样 没看出联动 实在不好意思

**Comment by KunMinX** [comment]
@zzm123456  哈哈，没关系的，感谢你对源码的认真阅读和反馈！

**Comment by zzm123456** [comment]
@KunMinX 感谢回复
