### ISSUE TITLE
Demo中删除item数据错乱闪退

### ISSUE THREAD

**Issue by hegaojian** [KunMinX/Linkage-RecyclerView#12]
在Demo中，YoumiStoreSampleFragment --》右边adapter 的删除功能按钮点击事件中取值是直接用了position，然后在删除功能中，删除这个position的item，最后调用了notifyItemRemoved来刷新适配器，第一次删除是没问题的，但是后面再删除的时候position会不对，因为使用了notifyItemRemoved 来刷新，但是adapter中的position是final修饰不会改变的，所以后面删除position都会错乱，应该在删除取值的时候使用hold.getAdapterPosition的值

 holder.getView(R.id.iv_goods_add).setOnClickListener(v -> {
                removeItem(holder.getAdapterPosition());
            });

**Comment by KunMinX** [comment]
@hegaojian 非常感谢你对源码的认真阅读、测试、和详细的反馈！现已修正 demo
