### ISSUE TITLE
反馈两个问题

### ISSUE THREAD

**Issue by RFlame** [KunMinX/Linkage-RecyclerView#14]
1.右侧RecycleView的HeaderView和公用的浮动的HeaderView，不是同一个view，如果我要在HeaderView新增字段（如header显示个数，但是左侧不显示个数），这样我就必须修改库的源码，添加公用的浮动的HeaderView显示个数的代码；
2.点击左侧RecycleView的最后一个item，左侧会依次滚动到最后一个，右侧也会依次滚动，当我数据比较多的时候，滚动时间会比较长，影响体验。

**Comment by KunMinX** [comment]
@RFlame 你好，LRV 当前的目标是服务于普适的 二级联动列表的需求，因此在实现一行代码接入功能的同时，尽可能地放开让用户从外部定制。
关于你提到的第一点，这就要求该库在内部支持联动逻辑的前提下，做出更灵活、更解耦的设计。我们预计会在下一个重大版本时解决这个问题。
关于第二点，可以通过 LRV.setScrollSmooth(false) 解决。

**Comment by RFlame** [comment]
好的，多谢
