### ISSUE TITLE
将Foot高度设置为warp，右边最后一个栏目没有充满全屏时，左边无法点击到最后一个

### ISSUE THREAD

**Issue by hegaojian** [KunMinX/Linkage-RecyclerView#17]

**Comment by KunMinX** [comment]
@hegaojian  
foot 高度就是特意设置为 match_parent，设置为 wrap_conten 是不可以的。
这是二级列表本身存在的业务硬伤，match_parent 是我给的解法，不这么做实在找不到恰当的理由去点击最后一个分组。
在源码中已注释说明。
