### ISSUE TITLE
当二级列表数据过多

### ISSUE THREAD

**Issue by tutuoo** [KunMinX/Linkage-RecyclerView#20]
需要分页加载数据，该如何处理滑动二级列表或者点击一级标题如何加载

**Comment by KunMinX** [comment]
@tutuoo 
目前考虑到的是常规场景，二级列表的数据能一次性全部加载。

如果是分页加载，需要前后端配合，将分组数据和具体数据分开提供。

针对这种非常规情况，如有需要，建议参考 linkageRecyclerView 中 onScroll 方法的联动逻辑，进行改造。

**Comment by wei6718189** [comment]
想问一下，这个库有老版本支持support library嘛 ？因为项目中和Androidx有兼容问题,改动成本有点大，有产品已经上线了

**Comment by KunMinX** [comment]
@wei6718189 
你好，support 库已经接近 2 年不更新了，因此本库不打算支持 support。

如果需要使用 support 的话，你可以将本库 clone 到本地，将 androidX 的依赖逐个替换为 support。

需要改动的内容仅限于 linkageRecyclerView 和 Adapter 等类和布局，所以如有需要，应该很快的。

只不过这样意味着 不自动接收本库后续的更新了。
