### ISSUE TITLE
问一下作者，secondaryAdapter.initData(groupedItems)不刷新数据啊

### ISSUE THREAD

**Issue by lidanning** [KunMinX/Linkage-RecyclerView#22]
购物车清空后我想刷新列表，使用
LinkageSecondaryAdapter secondaryAdapter = linkage.getSecondaryAdapter();
        secondaryAdapter.notifyDataSetChanged();
不刷新，使用secondaryAdapter.initData(groupedItems);也不刷新

**Comment by lidanning** [comment]
大神不好意思啊，自己处理的有问题已经解决了。

**Comment by dirkshowtime** [comment]
> 购物车清空后我想刷新列表，使用
> LinkageSecondaryAdapter secondaryAdapter = linkage.getSecondaryAdapter();
> secondaryAdapter.notifyDataSetChanged();
> 不刷新，使用secondaryAdapter.initData(groupedItems);也不刷新

问下。。我也是这个问题。。。数据源的list只做clear addAll 操作，notifyDataSetChanged不起作用

**Comment by marren06** [comment]
@lidanning 请问你们是怎么适配的数据啊？ 后端定制了？
