### ISSUE TITLE
你好 我发现这个库再系统5.1.1的时候onBindViewHolder一直执行很多次，麻烦帮忙看看呢

### ISSUE THREAD

**Issue by NickTet** [KunMinX/Linkage-RecyclerView#23]
你好 我发现这个库再系统5.1.1的时候onBindViewHolder一直执行很多次，麻烦帮忙看看呢

**Comment by KunMinX** [comment]
@NickTet  其他系统不会出现，唯独 5.1.1 会 是吗

**Comment by NickTet** [comment]
但是现在是进去就一次性把数据全部绑定了 假如一次性一万条数据 onBindViewHolder 就一次性执行一万次  recyler照道理说不是这样的吧

**Comment by KunMinX** [comment]
@NickTet 
很遗憾，这边无法复现你提到的问题。
对于屏幕可见的 item，onBindViewHolder 都会全部绑定。
另外 RecyclerView 的 API 是独立于系统版本的，5.1.1 会出错，那么其他系统也会出错，绝不可能就 5.1.1 “有问题”。

**Comment by KunMinX** [comment]
@NickTet 
为我的疏忽向你道歉。
感谢你的耐心测试和反馈，目前在 二级列表中 复现了你提到的这个情况。
已向 Google 小组反馈了 RecyclerView 在 5.1.1 下的这个问题。

**Comment by NickTet** [comment]
其实我也想不通 照道理recylerview是单独的support代码 不应该存在版本问题的 而且应该是Linkage-RecyclerView哪里存在小问题 我项目其他recylerview不会出现这种情况 证明不是recylerview的问题

**Comment by KunMinX** [comment]
@NickTet 
嗯，我刚刚试了下，简单地配置一个 RecyclerView，是没有问题。
而将 一级列表简化到原始最精简状态，仍然有全部加载的情况。（目前已提交测试数据）
因为忙碌的缘故，这个问题会留在未来合适的时候深入诊断和解决。

**Comment by NickTet** [comment]
那个一直绑定的问题修改Linkage-RecyclerView 的xml文件就行了 recylerview的宽度写死

**Comment by KunMinX** [comment]
@NickTet 非常感谢你的尝试和分享的方案！
