### ISSUE TITLE
cannot find symbol class FragmentElemeBinding

### ISSUE THREAD

**Issue by waleedmakarem** [KunMinX/Linkage-RecyclerView#24]
Dear Sir,
Thanks for your very nice library Linkage-RecyclerView   . However, when I add the reference to gradle :

implementation 'com.kunminx.linkage:linkage-recyclerview:1.9.0'

then when i try to define below object:

private FragmentElemeBinding mBinding;

I get below error:
error: cannot find symbol class FragmentElemeBinding

This class seems not included into the library.

**Comment by KunMinX** [comment]
@waleedmakarem 

Hi there:
Thanks for your trying, 
this reference only provide the Linkage-RecyclerView module.

the ElemeSampleFragment is just an example.
if you would like to define the FragmentElemeBinding,
you need to support DataBinding first,

for more detail:
https://developer.android.google.cn/topic/libraries/data-binding
