### ISSUE TITLE
关于Kotlin中init方法

### ISSUE THREAD

**Issue by YxmCute** [KunMinX/Linkage-RecyclerView#25]
我将demo 的fragment的代码转换为kotlin的，遇到LinkageRecyclerView.init()，第一个方法参数列表无法转换。
[截图](https://sm.ms/image/6rTbjGKRpZY5MvO)

**Comment by KunMinX** [comment]
@YxmCute 试试将 json 转换结果赋予给 MutableList，而不是 List，因为 kotlin 下的 List 反映的是不可变数组，类似于 Java 数组，而不是集合框架。

**Comment by YxmCute** [comment]
你好，感谢回复，我试过的，也是不行的。init()里面提醒的是需要 List<Nothing>?

**Comment by KunMinX** [comment]
@YxmCute 很遗憾，对 kotlin 没有深入的研究，暂时无法解答这个问题。不妨咨询一下身边使用 kotlin 的朋友，在使用 Java 方法时，如何正确地注入 List 参数。

**Comment by gzpaiwxc** [comment]
@YxmCute 想问大佬解决了这个 kotlin init() 的问题没有 ? 我也是用 kotlin 调用 init() 方法不行

**Comment by magoo-lau** [comment]
@YxmCute 请问解决了 kotlin init调用问题了没有

**Comment by NeVaDaAAA** [comment]
@YxmCute 大佬这个问题解决了吗

**Comment by hqweb** [comment]
@YxmCute @gzpaiwxc @NeVaDaAAA @magoo-lau @KunMinX 请问大佬们解决了吗?

**Comment by hqweb** [comment]
我解决了
 val items = mutableListOf<BaseGroupedItem<ElemeGroupedItem.ItemInfo>>()
 val lin = LinkageRecyclerView<ElemeGroupedItem.ItemInfo>(context)
  lin.init(items, SwitchSampleFragment.ElemeLinkagePrimaryAdapterConfig(), SwitchSampleFragment.ElemeLinkageSecondaryAdapterConfig())

必须指定LinkageRecyclerView的泛型！！

不能直接使用控件id，因为这样系统没有给你指定泛型
![image](https://user-images.githubusercontent.com/27910906/116672879-45da6180-a9d5-11eb-8346-3222d1e0e64f.png)

**Comment by KunMinX** [comment]
@hqweb 🉑
