### ISSUE TITLE
关于footer的问题

### ISSUE THREAD

**Issue by houyinyu** [KunMinX/Linkage-RecyclerView#26]
我这边设置的GridMode,这个footer特别影响UI，好像没有看到相关去掉的api，大神能把这个去掉吗。
就现在的业务需求来说，个人觉得很多的场景都不需要这个footer

**Comment by KunMinX** [comment]
源码中有提到，footer 是用于解决一级联动列表问题的策略。
这是联动列表场景本身先天缺陷所致。
如不需要，可自行改源码。
