### ISSUE TITLE
指定item 显示到顶部

### ISSUE THREAD

**Issue by zouxianbincc** [KunMinX/Linkage-RecyclerView#27]
我看了一下，好像没有提供方法，指定item 显示到顶部
因为有一个需要是：
指定某个产品显示在顶部。所以需要这条item滚动到顶部

**Comment by KunMinX** [comment]
@zouxianbincc 
这个需求可以通过拿到 RecyclerView 来调用其 smoothScrollToPostion 这个 API 解决
