### ISSUE TITLE
页面刷新的问题

### ISSUE THREAD

**Issue by dirkshowtime** [KunMinX/Linkage-RecyclerView#29]
作者您好！
我再使用中遇到了个刷新的问题
数据源只做clear和addAll操作
linkage.getPrimaryAdapter().notifyDataSetChanged();
linkage.getSecondaryAdapter().notifyDataSetChanged();
上述代码不起作用
感谢

**Comment by KunMinX** [comment]
@dirkshowtime 看源码， adapter setList 的内部实现

**Comment by marren06** [comment]
@dirkshowtime 请问下 外部数据源改变页面怎么刷新呢? 我这边外部数据源改变只有左边列表有数据   右边列表没数据

请求数据完成数据适配好调用linkage.init(items, new ElemePrimaryAdapterConfig(), new ElemeSecondaryAdapterConfig());  
当再次请求数据时候 list.clear 后重新再 适配add新数据  但是页面不刷新 出现上面描述的情况。

请问你是怎么处理的？能给点思路吗？

万分谢谢！
