### ISSUE TITLE
@jianghao1123

### ISSUE THREAD

**Issue by CoderExplore** [KunMinX/Linkage-RecyclerView#3]
@jianghao1123 

实在看不出 “继承接口” 和 “局限于 JSON 数据” 有何因果关系。

JSON 只是结构化数据的方式之一，LinkageRecyclerView 并没有强制要求数据来源一定是 JSON，无论 XML，JSON，protocol buffer 还是何种方式，只要在能在移动端解析成 List<XXXGroupedItem> 即可。

此外，数据分组依赖于抽象类中仅有的几个必填字段，用户自定义的 XXXGroupedItem 须继承于抽象类 BaseGroupedItem。

_Originally posted by @KunMinX in https://github.com/KunMinX/Linkage-RecyclerView/issues/1#issuecomment-492066927_

**Comment by CoderExplore** [comment]
感谢分享， 这挺好的，只要提前跟后台沟通好，分分钟搞定联动。        不过我现在遇到一个老项目，后台根本没提供BaseGroupedItem中的字段，联动功能是用其他办法，比如分组是用StickyListHeaders实现。  如果现在我想引入你的项目重写这个功能，那还得去让后台也跟着改。    这就是上面所谓的“局限性”吧。    新手不懂，若讲的不对你说，我再删除。

**Comment by KunMinX** [comment]
@CoderExplore 

感谢反馈。

为了避免对其他使用者造成困扰，我再三请求不要使用 “局限性” 这种似是而非的描述，因为它不能明确地划清责任、找到问题、并真正着手处理问题。任何项目都需要前后端配合来交互数据，这是母庸质疑的。

你遇到的这个问题，属于老项目数据适配的问题。数据适配通常有两种解决方案，一种是直接从服务端拿到前后端协商好的数据进行 UI 展示，另一种是你提到的这种情况，我认为可以在移动端的 Model 层、在拿到服务端响应的数据后，自行完成二次适配，并最终将适配结果，递交给 UI 层展示。

**Comment by CoderExplore** [comment]
好的，  非常感谢你能解答我的疑惑。

**Comment by CoderExplore** [comment]
好的我明白了， 非常感谢你能解答我的疑惑。

**Comment by KunMinX** [comment]
@CoderExplore 

不客气。请让 issue 保持打开的状态，这可以帮助有着同样困惑的人迅速了解状况。

**Comment by marren06** [comment]
@KunMinX 请问下作者   在拿到服务端响应的数据后，自行完成二次适配  怎么实现？ 拿到我们自己的请求响应数据 怎么二次包装适配到 BaseGroupedItem 

如果BaseGroupedItem 这个实体类可以用户自定义的话 是不是更好点呢？个人建议不知道是否可行？  先感谢作者！

**Comment by KunMinX** [comment]
@marren06 
LinkageRV 设计的实体类，完全是基于该控件特性的需要，而且已经做到十分灵活。
我觉得情况是，你在自己吓自己，把事情想太复杂了。
事实上，拿到后端数据，根据 LinkageRV 的需要做一次适配，耗时顶多几十毫秒，和网络请求本身的耗时相比可以忽略不计。
具体可见 readme 中提供的 json 示例，就这么简单，没有额外多余的复杂的东西。
