### ISSUE TITLE
能不能吧最后end的布局 去掉或者弄成可以配置 不需要就不配置 ,需要就配置上去

### ISSUE THREAD

**Issue by yexseven** [KunMinX/Linkage-RecyclerView#30]
我在改的过长中 end布局去掉后 在GREATPHONE 这个fragment 中 上拉到最后2个时候 ,二级recylerview 的header 顶不上去 就卡在 倒数第二个 i 这个地方了

**Comment by KunMinX** [comment]
@yexseven 
这个源码中有交待。end 是为了规避 联动场景本身 客观存在的问题。
事实上，你可直接将 end item 的布局给自定义，而不是考虑去掉。
