### ISSUE TITLE
联动问题！

### ISSUE THREAD

**Issue by Wudelin** [KunMinX/Linkage-RecyclerView#31]
1.关于一级菜单和二级菜单具体的联动是怎么实现的？
2.二级菜单的滑动以及Title怎么处理？

。。表示能力有限，源码看了挺久的还是没想明白。！！

**Comment by KunMinX** [comment]
@Wudelin 
联动的发生并非魔术，都是实打实的逻辑在起作用。
联动逻辑主要集中在 linkageRecyclerView 类中 onScroll 回调那一小段代码（有简明的注释），
二级菜单滚动时触发边界条件 就会通知一级菜单滚动。

具体怎么看、怎么学，我不能替你做主。我的建议是，先掌握 recyclerView 的基本使用和 java 抽象思想，再来看 LRV 的源码，这样理解起来会方便一些。

**Comment by Wudelin** [comment]
好的 多谢了
