### ISSUE TITLE
数据适配

### ISSUE THREAD

**Issue by marren06** [KunMinX/Linkage-RecyclerView#32]
群主：

数据适配要么我们自己后台按照您demo定制接口（兼顾多端不太可能）
  要么自己看源码扩展数据适配吗？看源码短时间也摸不透  短时间内没法使用啊   建议群主数据适配能不能介绍下扩展方法

**Comment by KunMinX** [comment]
@marren06 
完全不需要后台的适配，
事实上，只需在 数据层 拿到从后端请求到的数据后，根据 Readme 中描述的 LinkageRV 数据格式的要求，自己做个适配，再推给 UI 层即可。

**Comment by marren06** [comment]
@KunMinX DefaultGroupedItem 您这个实体的字段我们后台完全不一样  要怎么做？  不明白

**Comment by KunMinX** [comment]
@marren06 
你新建个 group 类，继承 baseGroupItem，然后做适配的时候，遍历后端数据，把字段值都注入到 实例化的 group 对象中不就行了 …

**Comment by marren06** [comment]
@KunMinX 感谢群主！我好像明白了嘿嘿 苦笑 呲牙 强颜欢笑 憨笑

**Comment by KunMinX** [comment]
@marren06 
我知道你为什么会有迷惑了，
readme 中的 json 只不过是简单示例，实际上最终给 LinkageRV 用的还是 group List 列表对象，
我去 readme 中改进一下描述

**Comment by marren06** [comment]
群主  ：

怎么给两个构造同时赋值呢？

![image](https://user-images.githubusercontent.com/17778482/83215924-a09e8400-a19a-11ea-9b79-a0fb078a212f.png)
解析出来的数据通过一个ElemeGroupedItem 类 给值  

第一个
![image](https://user-images.githubusercontent.com/17778482/83215968-bf9d1600-a19a-11ea-930b-3069d800298a.png)UI 出来了   右边列表数据怎么同时赋值上去呢?

**Comment by marren06** [comment]
![image](https://user-images.githubusercontent.com/17778482/83219206-59b48c80-a1a2-11ea-9dd3-b0ebcb5b032f.png)
群主  库里封装的构造  为什么没有三个参数同时存在的构造方法？


我这样没法设置三个参数同时传递  只能选一个

**Comment by KunMinX** [comment]
@marren06 
这个拿项目原始 demo 调试一下就知道了呀
有 info 的就是普通 item，有 header 的就是 header item，是有区别的呀 …

**Comment by marren06** [comment]
可否加个Q  

如果方便请加 245646937 感谢！！

**Comment by marren06** [comment]
现在情况是 ![image](https://user-images.githubusercontent.com/17778482/83232062-19173c00-a1bf-11ea-8d4c-775956ee6495.png) 已经赋值成功了！
![image](https://user-images.githubusercontent.com/17778482/83232231-67c4d600-a1bf-11ea-943c-8593ca15961f.png)这块始终没有值  

不知道是不是这样？ 遍历后端集合数据 
![image](https://user-images.githubusercontent.com/17778482/83232231-67c4d600-a1bf-11ea-943c-8593ca15961f.png)

**Comment by marren06** [comment]
您好作者：

我通过仔细研究发现您demo的数据结构和我们后端的结构不一样
![image](https://user-images.githubusercontent.com/17778482/83963086-d26bc500-a8d5-11ea-98a3-e27b6d94a03a.png)

您这个一旦header设置ture 右面的iteminfo就设置null了，

只有 header 设置false的时候 iteminfo才可以赋值

那么对于我们给的后端给的 我不知道要怎么样赋值 ：

我们的数据：
![image](https://user-images.githubusercontent.com/17778482/83963099-e31c3b00-a8d5-11ea-8a1e-f4cb3ba729c0.png)


怎么既能header设置true 也可以iteminfo也可以赋值

下面是我赋值的代码：
![image](https://user-images.githubusercontent.com/17778482/83963101-e7e0ef00-a8d5-11ea-82ee-08562a42f606.png)

这样的赋值只能显示一级列表也就是左边的列表显示 右边显示不了？ 请问：

是不是要我们后端更改返回数据的形式呢？ 类似上面第一张图片那样？

麻烦作者，再次感谢！！！

**Comment by marren06** [comment]
@KunMinX 群主麻烦您给我解解惑？困扰几天了  万分感谢！

**Comment by KunMinX** [comment]
@marren06 
你这个就没用对，LRV 是按显示顺序来的，
不管是 header 还是 info，都是单独一行，不存在包含的关系，这样说能理解吗，
你相当于给 header 的 groupedItem 又添加了 info，这肯定是不行的，
你每个 shop 的 item 都应该重新 new 一个 groupedItem 来注入，
grouped 不是组的意思，而是 “可分组的” 的意思。

**Comment by marren06** [comment]
@KunMinX 还是不明白,这两个集合遍历要把数据装进总的  
 linkage.init(items, new ElemePrimaryAdapterConfig(), new ElemeSecondaryAdapterConfig());

items 里面  要么是ElemeGroupedItem elemeGroupedItem = new ElemeGroupedItem(true, s.getCityName()); 设置true  要么设置false  怎么同时显示呢?  最终不是要
linkage.init(items, new ElemePrimaryAdapterConfig(), new ElemeSecondaryAdapterConfig()); 赋值总的items集合嘛！

麻烦您根据楼上我们的数据能不能写个伪代码  ？  麻烦您了！

**Comment by KunMinX** [comment]
@marren06 
```java
List<XXXItem> list = new Arraylist;
for(shop s : shoplist ){
    XXXitem headeritem = new XXXItem(true, s.cityName);
    list.add(headerItem);
    for( shopinfo info: s.getShop){
        XXXitem infoItem = new XXXItem(false, info);
        list.add(infoItem);
    }
}

linkage.init(list);

```

**Comment by marren06** [comment]
额....   我自己傻了 ~-~ 万分感谢！

**Comment by marren06** [comment]
请问下群主，我接口数据实现搜索数据怎么更新，请求下搜索的数据还是一样init吗？我试了列表不起作用

**Comment by KunMinX** [comment]
@marren06 
原则上，我不参与使用者的实际项目答疑，因为没有一致的背景来做交流的前提。
遇到问题首先做的就是断点调试，要么是新注入的数据结构不对导致过程中崩了，要么就是其他原因。

最后，群里没见过有叫 marren 的小伙，在公共场合被戴个 “群主” 的高帽让我很不舒服，再看到类似称呼的留言，我就当没看见。

**Comment by marren06** [comment]
> @marren06 
> 原则上，我不参与使用者的实际项目答疑，因为缺乏一致的背景来做有效交流的前提。
> 遇到问题首先做的就是断点调试，要么是新注入的数据结构不对导致过程中崩了，要么就是其他原因。
> 
> 最后，不管是不是读者群的群友，在公共场合被戴个 “群主” 的高帽让我很不舒服，再看到类似称呼的留言，我就当没看见。
> 
不好意思，我真心没有给您戴高帽的感觉，可能之前在群里问问题习惯性的这样称呼了您，我在这条issues上面请教您都是尊称您“作者”，可能这次请教是在公交车上用Github app提交的问题，有点仓促，在此给您道歉。

这个刷新的问题，我调试了很久，接口数据源改变，上面赋值操作一点都没有变化，列表并没有想我想象是我搜索出来的数据，可能是我调试的不够仔细，我明天再调试下，感谢您！

**Comment by KunMinX** [comment]
我不是公司项目的参与人员，我越界提供建议，一来是在干涉，二来沟通效果奇差，因为公司项目我不方便知道、也不知道实情。

我这里仅就自己的经验提供两个通用方案：

1.属于产品设计问题。联动列表设计的典型是 美团外卖、饿了么，那么搜索的设计应以 外卖软件为参考，外卖软件对于关键搜索都是另外打开页面，用普通的列表来直接呈现结果，而不是折腾联动列表。

2.如果真要折腾联动列表，可以直接在本库的 sample 中添加搜索的 demo，拿假数据测试，方便发现端倪，而不是一边在公司项目折腾，一边又无法公开数据与网络上的其他人沟通。

**Comment by NicodeLee** [comment]
@marren06 请问一下用那个json格式化工具或者那个编辑器的，这个json数据好多在线的json格式化工具都没办法排版

**Comment by marren06** [comment]
@NicodeLee 
![image](https://user-images.githubusercontent.com/17778482/103204320-0ec64780-4932-11eb-9646-3e981b905304.png)
