### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by Lancerer** [KunMinX/Linkage-RecyclerView#33]
当数据量大了，一个header里面有十几个itemInfo，然后有几十个header，而且iteminfo的数据是通过header中的id获取的，这样在initLinkageDatas要循环请求iteminfo，请问这样会造成卡顿嘛

**Comment by KunMinX** [comment]
@Lancerer 
header 和 info 是平级的独立的 item

**Comment by Lancerer** [comment]
> @Lancerer
> header 和 info 是平级的独立的 item

就是因为是平级的，但是我的info是要通过header获取的，只有info和header全部获取完我才能initLinkageDatas，这样下来数据量感觉有点大

**Comment by KunMinX** [comment]
@Lancerer 
那自行改造或另请高明吧。优先加载高频的 header，低频的 info 延后加载。

**Comment by Lancerer** [comment]
> @Lancerer
> 那自行改造或另请高明吧（你这个场景其实适合可折叠的那种 recyclerview 设计）。优先加载高频的 header，低频的 info 延后加载。
