### ISSUE TITLE
建议rv_primary的宽度改为可配置

### ISSUE THREAD

**Issue by luppiterw** [KunMinX/Linkage-RecyclerView#34]
layout_linkage_view.xml中左侧组列表的宽度目前貌似是100dp固定的：

`    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/rv_primary"
        android:layout_width="100dp"
        android:layout_height="match_parent" />`

感觉改成配置比较好，毕竟每个设备上表现不太一样。

**Comment by KunMinX** [comment]
@luppiterw 

感谢反馈
