### ISSUE TITLE
底部的footview会重复加载数据的bug

### ISSUE THREAD

**Issue by Yangwenhua44** [KunMinX/Linkage-RecyclerView#36]
将Linkage-RecyclerView放在dialog里面加载,每次dimiss之后,在打开.二级菜单的底部footview都会增加一个,每次都增加一个?这是啥bug为什么之后底部的footview会重复加载数据?其他的都显示正常

**Comment by KunMinX** [comment]
@Yangwenhua44 
无法复现，也许是数据结构的问题，请参考 readme 中对 header 和 info 的组织。
此外，可运行本项目示例，查阅第四个页面 “DIALOG” 的表现。

**Comment by Yangwenhua44** [comment]
好的，谢谢




    


在2020年09月12日 01:29，KunMinX 写道： 
@Yangwenhua44
无法复现，也许是数据结构的问题，请参考 readme 中对 header 和 info 的组织。
此外，可运行本项目示例，查阅第四个页面 “DIALOG” 的表现。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/KunMinX/Linkage-RecyclerView/issues/36#issuecomment-691221613",
"url": "https://github.com/KunMinX/Linkage-RecyclerView/issues/36#issuecomment-691221613",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
