### ISSUE TITLE
getSecondaryAdapter().getItems() 获取实体类强转报错

### ISSUE THREAD

**Issue by p7nkie** [KunMinX/Linkage-RecyclerView#37]
你好 
List<***> items = linkage.getSecondaryAdapter().getItems();
在获取适配器中的数据后遍历报错:
java.lang.ClassCastException: com.kunminx.linkage.bean.DefaultGroupedItem cannot be cast to ***
这种错误,得不到想要的实体类
可以给解答一下吗

**Comment by KunMinX** [comment]
@p7nkie 
请检查实体类的继承关系。
所有联动逻辑都是基于 BaseGroupedItem 来控制，
所以项目中使用的 GroupedItem 例如 DefaultGroupedItem，须继承于 BaseGroupedItem。
具体可参考项目中的示例。

**Comment by p7nkie** [comment]
可是都按照demo继承过了呀，列表都可以正常显示
就是获取数据的时候会出现这种错误
很苦恼@@

**Comment by KunMinX** [comment]
@p7nkie 
不需要强转。xxxGroupedItem 继承于 BaseGroupedItem（注意是 BaseGroupedItem 不是 DefaultGroupedItem），拿到 xxxGroupedItem 就可以使用。

**Comment by p7nkie** [comment]
就是继承的BaseGroupedItem
不强转的话出来的是Object对象 用不了呀

**Comment by p7nkie** [comment]
> 就是继承的BaseGroupedItem
> 不强转的话出来的是Object对象 用不了呀

**Comment by p7nkie** [comment]
你好 发现问题了 
为什么框架最后会加一条DefaultGroupedItem 这个数据呢?
还有最后的The End 怎么去掉呀

**Comment by KunMinX** [comment]
@p7nkie 
the end 是为了规避联动列表在产品层面的先天缺陷，
具体可翻看之前的 issue，
如不需要，可在 SecondaryAdapterConfig 中为 getFooterLayoutId 传个空白 view 的 layout 的 id，
具体参考示例。

**Comment by p7nkie** [comment]
好的 非常感谢!!!

**Comment by foxluo9527** [comment]
我也遇到了这个问题，直接复制demo的ElemeGroupedItem类，报错java.lang.ClassCastException: com.foxluo.ordering.bean.ElemeGroupedItem$ItemInfo cannot be cast to com.kunminx.linkage.bean.DefaultGroupedItem$ItemInfo
，请问是如何解决的

**Comment by foxluo9527** [comment]
> 好的 非常感谢!!!
我也遇到了这个问题，直接复制demo的ElemeGroupedItem类，报错java.lang.ClassCastException: com.foxluo.ordering.bean.ElemeGroupedItem$ItemInfo cannot be cast to com.kunminx.linkage.bean.DefaultGroupedItem$ItemInfo
，请问是如何解决的
