### ISSUE TITLE
调皮 linkage-recyclerview  build.gradle 47行 多了 }

### ISSUE THREAD

**Issue by bayshier** [KunMinX/Linkage-RecyclerView#4]

**Comment by KunMinX** [comment]
@bayshier 谢谢反馈

**Comment by 2422918668** [comment]
> @bayshier 谢谢反馈

Process 'command 'D:\AS_Sdk\build-tools\27.0.3\aapt.exe'' finished with non-zero exit value 1
引入依赖之后会提示这个错误,不知道多了个}的缘故

**Comment by KunMinX** [comment]
@2422918668 

你是在自己的主干工程中依赖本库吗？

检查一下主干工程是否使用的是 support library。因为本开源库是基于 Google 最新的 AndroidX 开发的。Google 已不再维护 support library，所以如果是在个人练手项目中引用的话，请适配 AndroidX。

**Comment by 2422918668** [comment]
项目里用到了support library,请问可以使用这个库吗?

**Comment by KunMinX** [comment]
@2422918668 你需要将主干项目适配 AndroidX，不然和该库不兼容的。考虑到 support library 不再维护，该库不会出 support library 版。

**Comment by 2422918668** [comment]
好的,谢谢解惑!!!
