### ISSUE TITLE
GridMode模式有ui问题

### ISSUE THREAD

**Issue by caik123** [KunMinX/Linkage-RecyclerView#40]
设置模式为GridMode模式，并且SPAN_COUNT_FOR_GRID_MODE为2时，当最后一行不到2个item，那么最后一行的item就会很长。demo是由于item的背景色跟底部的背景色一致所以看不出问题，当将demo中adapter_eleme_secondary_grid.xml的背景色设置为其他颜色，可以很快看出问题。

**Comment by KunMinX** [comment]
@caik123 

感谢反馈，可以通过 mLinkageRecyclerView.setRvSecondaryBackground() 解决

**Comment by caik123** [comment]
> @caik123
> 
> 感谢反馈，可以通过 mLinkageRecyclerView.setRvSecondaryBackground() 解决

**Comment by caik123** [comment]
@KunMinX 你好，你可能没仔细看issue描述，问题不是second recyclerview的background背景色怎么设置，是**当最后一行不到2个item，那么最后一行的item就会很长**，可惜不能贴图，要不然就很容易描述问题了。很简单，你将adapter_eleme_secondary_grid.xml这个文件背景色设置为#00ff00，然后点击LESS PRIMARY ITEM底部的“你饿了么”按钮，就会发现问题。

**Comment by KunMinX** [comment]
@caik123 

感谢你的细心反馈，已修复，可更新到最新源码查阅
