### ISSUE TITLE
请问怎么自定义HeaderView

### ISSUE THREAD

**Issue by bibubi** [KunMinX/Linkage-RecyclerView#42]
想实现自定义Header,而不是单纯的一个TextView.
尝试过更改Header所在的Layout文件,但是只能TextView有"被顶上去"的效果,其余View则无办法"被顶上去"

**Comment by KunMinX** [comment]
@bibubi 

感谢反馈，已更新 header 的功能，可 pull 最新源码到 custom header sample fragment 中查阅
