### ISSUE TITLE
发现小Bug

### ISSUE THREAD

**Issue by bibubi** [KunMinX/Linkage-RecyclerView#43]
![Snipaste_2021-01-22_19-48-49](https://user-images.githubusercontent.com/18078927/105487463-1a1b5180-5ceb-11eb-9551-a0e5ba3fed68.png)
无论是否自定义HeaderView,都存在这现象

**Comment by KunMinX** [comment]
@bibubi 

你还是通过 sm.ms 网站获取截图链接吧，不然我这边图床崩了看不见

**Comment by bibubi** [comment]
![105487463-1a1b5180-5ceb-11eb-9551-a0e5ba3fed68.png](https://i.loli.net/2021/01/23/wW48KTE6xlRo3H1.png)

**Comment by bibubi** [comment]
另外希望加入Grid显示格式下, 各个item之间的自定义间距

**Comment by KunMinX** [comment]
@bibubi 

好的，已更新
