### ISSUE TITLE
关于新增Decoration,无法判断行数、列数问题

### ISSUE THREAD

**Issue by bibubi** [KunMinX/Linkage-RecyclerView#45]
![Screenshot_20210123_170930_com.kunminx.linkagerecyclerview.jpg](https://i.loli.net/2021/01/23/PyZ1GUvQ8jOMNmp.jpg)
![Screenshot_20210123_170842_com.kunminx.linkagerecyclerview.jpg](https://i.loli.net/2021/01/23/PCzbuEXkjsmVerT.jpg)

不知道是我不会设置还是代码问题，当不知道源数据个数的情况下，无法判断行数、列数，从而造成排版混乱。
而且Decoration也会影响到HeaderView

**Comment by KunMinX** [comment]
@bibubi 

你想要设置间距的话，那只能先由你来负责编写和调试啦 😄

提示：
1.可以直接在 linkage 库源码中改写，可以在 linkageRV 类中添加 itemDecoration 内部类，以便拿到 secondaryAdapter、position 和 item，
2.或者通过 (GridLayoutManager) mSecondaryLayoutManager.getSpanSizeLookup().getSpanCount 拿到当前行实际的 spanCount（源码中已为 header 和 info 分别设置了不同的 spanCount）

二者都对判断和处理 offset 的添加与否能提供帮助。

**Comment by KunMinX** [comment]
刚刚上传了 decoration 示例到 app module，感兴趣可到 custom decoration sample fragment 中参考，实际项目中的使用请自行调整和完善
