### ISSUE TITLE
接#45 Decoration问题

### ISSUE THREAD

**Issue by bibubi** [KunMinX/Linkage-RecyclerView#46]
#45 在Demo中,使用源数据个数都是双数.刚好填满2列数据. 如果在源数据个数单双数不确定的情况下,还是会出现无法判断column的问题..研究了几天还是没研究出来

**Comment by KunMinX** [comment]
@bibubi 

多给自己一点时间，相信自己，你可以的，

并且这个问题属于 RecyclerView 高频使用的问题，如果你想在 itemDecoration 的使用上轻车熟路，这个探索的过程是不可避免的。

**Comment by KunMinX** [comment]
提示：实现最简单、副作用也最小的思路是
在遍历生成列表数据的过程中，自动判断当前组的 item 数是否能凑齐整行，不能的话就额外加几个空数据来占位。
