### ISSUE TITLE
数据操作怎么办？加一个或减一个 group 或 item 怎么刷新？

### ISSUE THREAD

**Issue by lishangwl** [KunMinX/Linkage-RecyclerView#48]
数据操作怎么办？加一个或减一个 group 或 item 怎么刷新？
现在你可以通过 LinkageRecyclerView 拿到一二级 adapter，并通过拿到 adapter 的数据，来完成数据的操作和列表的刷新。（具体可以参考 YoumiStoreSampleFragment）
demo里没有YoumiStoreSampleFragment

**Comment by KunMinX** [comment]
原 issue 类名已修正。

你想加减 item 的话，可参考 LessPrimaryItemSampleFragment 类的示例自行测试和修改。
