### ISSUE TITLE
【FAQ - 集中答疑帖】关于数据适配、Gradle依赖等

### ISSUE THREAD

**Issue by KunMinX** [KunMinX/Linkage-RecyclerView#5]
请勿跟帖，如有 issue，请另外开辟一个新帖。本帖专用于总结网友提过的问题和我提供的答疑。

**Comment by hotgalvanizing** [comment]
引入项目之后编译报错：ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.1.0-alpha05] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-27:19 to override.

**Comment by KunMinX** [comment]
@hotgalvanizing 详见 https://github.com/KunMinX/Linkage-RecyclerView/issues/4#issuecomment-493016819
