### ISSUE TITLE
这个库可以实现多级联动吗

### ISSUE THREAD

**Issue by LuckyYangs** [KunMinX/Linkage-RecyclerView#53]

**Comment by KunMinX** [comment]
此库专门解决二级联动的场景，如外卖订餐场景，你想实现多级联动的话，可以搜寻日期对话框之类的开源库，从中获取实现逻辑

**Comment by LuckyYangs** [comment]
> 此库专门解决二级联动的场景，如外卖订餐场景，你想实现多级联动的话，可以搜寻日期对话框之类的开源库，从中获取实现逻辑

感谢
