### ISSUE TITLE
距离最远的主菜单点击切换 滑动的时间是否可以调节

### ISSUE THREAD

**Issue by vxinv** [KunMinX/Linkage-RecyclerView#56]
距离最远的主菜单点击切换，感觉滑动的时间很长，是否可以配置参数缩短时间

**Comment by vxinv** [comment]
可以设置平滑滚动

**Comment by NicodeLee** [comment]
关掉平滑滚动就行。
linkageRecyclerView.setScrollSmoothly(false);
