### ISSUE TITLE
程序包不存在

### ISSUE THREAD

**Issue by dreamozilla** [KunMinX/Linkage-RecyclerView#59]
implementation 'com.kunminx.linkage:linkage-recyclerview:2.6.0'  后提示程序包不存在

以下2个没有引入
import com.google.android.material.tabs.TabLayoutMediator;     （这个可以引入后消除提示）
import com.kunminx.linkagelistview.databinding.ActivityMainBinding;（这个不行）

错误: 程序包com.kunminx.linkagelistview.databinding不存在

**Comment by KunMinX** [comment]
可以对照实验排查，

在本项目的 sample module 中通过远程依赖而非 module 依赖，来引入 linkage-recyclerview，

如果没有上述问题，那就自行排查自己的项目

**Comment by dreamozilla** [comment]
找到了，谢谢
