### ISSUE TITLE
悬浮窗使用会报错

### ISSUE THREAD

**Issue by chengzhuangjie** [KunMinX/Linkage-RecyclerView#61]
崩溃信息:
Binary XML file line #20 in com.wechat.miao:layout/default_adapter_linkage_secondary_linear: Error inflating class <unknown>

类名:null

方法:null

行数:0

类型:null

时间:2022-10-25_19:42

设备名称:M2012K11AC

设备厂商:Redmi

系统版本:Android 11-30

CPU-ABI:arm64-v8a

versionCode:null

versionName:null

全部信息:
null

**Comment by KunMinX** [comment]
根据你提供的信息，很难诊断具体发生了什么哈。
可以尝试使用自定义的二级 layout，具体使用参考 sample 案例。
