### ISSUE TITLE
🚩BaseGroupedItem 只支持String类型的header, 能不能支持对象类型

### ISSUE THREAD

**Issue by minitriangle** [KunMinX/Linkage-RecyclerView#62]
🚩BaseGroupedItem 只支持String类型的header, 能不能支持对象类型。
或者ILinkagePrimaryAdapterConfig 支持返回position也好的.
有些使用场景需要显示分类的badge, 可是primaryAdapterConfig 只能获取String的标题，也无法获取position.

**Comment by KunMinX** [comment]
见 CustomJsonSampleFragment 示例

**Comment by minitriangle** [comment]
我不是数据自定义需求，是实现ILinkagePrimaryAdapterConfig 这个接口，
在 onBindViewHolder(LinkagePrimaryViewHolder holder, boolean selected, String title) 里不能获取当前position, 只有header的标题文字和选中状态，无法自定义处理.（比如特定标题颜色自定义，添加badge，按position 特定处理等）。
期望的实现方法是 
onBindViewHolder(LinkagePrimaryViewHolder holder, boolean selected, String title, BaseGroupedItem.ItemInfo ItemInfo)
或
onBindViewHolder(LinkagePrimaryViewHolder holder, boolean selected, String title, int position)

**Comment by KunMinX** [comment]
一级列表目前提供的数据输出确实有限，如有定制化需求，建议是将本库的代码 fork 一份，自行修改和使用

**Comment by KunMinX** [comment]
明白你意思了，可以通过 onBindViewHolder 方法的参数 1  LinkagePrimaryViewHolder 来获取符合预期的 position，

当初没有直接提供 position 也是出于这个考虑，

```java
  public interface OnPrimaryItemClickListener {
    /**
     * we suggest you get position by holder.getAdapterPosition
     *
     * @param holder primaryHolder
     * @param view   view
     * @param title  groupTitle
     */
    void onItemClick(LinkagePrimaryViewHolder holder, View view, String title);
  }
```

**Comment by minitriangle** [comment]
谢谢，我真没注意LinkagePrimaryViewHolder 的这些方法

**Comment by minitriangle** [comment]
谢谢，我真没注意LinkagePrimaryViewHolder 的这些方法
