### ISSUE TITLE
请问怎么隐藏二级菜单

### ISSUE THREAD

**Issue by wsdydeni** [KunMinX/Linkage-RecyclerView#63]

**Comment by KunMinX** [comment]
这控件本就是用于一二级菜单联动，没懂为啥要隐藏二级菜单哈。

如有定制需求，建议是本库代码拷贝到项目中，自行根据需求改造。

**Comment by wsdydeni** [comment]
> 这控件本就是用于一二级菜单联动，没懂为啥要隐藏二级菜单哈。
> 
> 如有定制需求，建议是本库代码拷贝到项目中，自行根据需求改造。

感觉显示隐藏二级菜单应该是中等需求的功能把，麻烦你大佬你有空加上吧

**Comment by KunMinX** [comment]
说实话真没懂哈。个人喜欢保持功能纯粹，除非典型使用场景。

并且由于这是开源库，对于特殊定制需求，本就可以拷贝代码和修改哈。
