### ISSUE TITLE
当一级选项的数据比较多时，显示会错乱

### ISSUE THREAD

**Issue by ydmmocoo** [KunMinX/Linkage-RecyclerView#7]
当一级选项的数据比较多，超过一个屏幕，滑动二级选项或者直接滑动一级选项可看到数据显示有问题

**Comment by ydmmocoo** [comment]
左侧列表超过屏幕高度不进行滚动

**Comment by KunMinX** [comment]
@ydmmocoo 是截至 2019.5.23 的最新代码运行的结果吗？

**Comment by ydmmocoo** [comment]
是的，我试了最新的代码也有这个问题，你可以多加点数据测试下

**Comment by KunMinX** [comment]
@ydmmocoo 最新代码在 GreatPhone 页面中安排了20个左侧 item，当二级item滚动到 m 分组时，一级没有显示出最后一个 m item，需要手动向上滑才能看到，你想表达的是这个意思吗？

**Comment by ydmmocoo** [comment]
嗯，这是一个，还有就是左侧的选中和未选中状态好像也会错乱

**Comment by KunMinX** [comment]
@ydmmocoo 好的。这些问题将在今后的版本中诊断和修复，感谢你的反馈！

**Comment by KunMinX** [comment]
@ydmmocoo 你好，在刚刚发布的 2019.5.24 的版本中，通过采用全新的 select 机制，解决了你提到的这个问题。

由于精力有限，我暂时没能诊断我自己提出的 “一级items无法自动滚动到底” 的问题，如果你恰好有这方面的经验，请不吝赐教！
