### ISSUE TITLE
点击右侧列表的添加按钮，怎么刷新数据，有接口吗

### ISSUE THREAD

**Issue by wangfeng19930909** [KunMinX/Linkage-RecyclerView#9]

**Comment by KunMinX** [comment]
@wangfeng19930909 源码有详尽的示例。请先认真阅读源码。

**Comment by wangfeng19930909** [comment]
看了下源码，还是感觉刷新列表不怎么方便，点击添加或减少按钮要刷新列表商品数量




------------------ 原始邮件 ------------------
发件人: "KunMinX"<notifications@github.com>;
发送时间: 2019年5月24日(星期五) 下午5:20
收件人: "KunMinX/Linkage-RecyclerView"<Linkage-RecyclerView@noreply.github.com>;
抄送: "王峰"<1300497680@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [KunMinX/Linkage-RecyclerView] 点击右侧列表的添加按钮，怎么刷新数据，有接口吗 (#9)




@wangfeng19930909 源码有详尽的示例。请先认真阅读源码。

**Comment by KunMinX** [comment]
@wangfeng19930909 好的，这个需求我记下了。我再想想怎么把adapter解耦得更彻底，完全交给用户自己去实现，可能会放在2.0.0版推出。
